### 전체 공항 목록 조회
GET http://localhost:8080/api/mcp/airports

### 공항 코드 조회
GET http://localhost:8080/api/mcp/airports/code?airportName=광주


### 전제 항공사 목록 조회
GET http://localhost:8080/api/mcp/airlines

### 항공사 ID 조회
GET http://localhost:8080/api/mcp/airlines/id?airlineName=아시아나항공

### 항공편 조회
GET http://localhost:8080/api/mcp/flight/search?depAirportId=NAARKJJ&arrAirportId=NAARKPC&departmentDate=20260610

